"""Branded, page-safe PDF exports for hospital reports.

The builders return bytes so views can stream a response without writing
patient or financial information to a temporary file.
"""

from io import BytesIO
from xml.sax.saxutils import escape

from django.utils import timezone
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

NAVY = colors.HexColor("#0B1F38")
TEAL = colors.HexColor("#087F8C")
INK = colors.HexColor("#172436")
MUTED = colors.HexColor("#5D6878")
LINE = colors.HexColor("#D9E0E8")
PALE = colors.HexColor("#F2F7F8")
WARNING = colors.HexColor("#8B5200")


def _money(value):
    return f"KES {value:,.2f}"


def _text(value):
    return escape(str(value or ""))


def _styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name="KFBTitle", parent=styles["Title"], fontName="Helvetica-Bold",
        fontSize=19, leading=23, textColor=NAVY, alignment=TA_LEFT,
        spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        name="KFBMeta", parent=styles["Normal"], fontName="Helvetica",
        fontSize=8.5, leading=12, textColor=MUTED,
    ))
    styles.add(ParagraphStyle(
        name="KFBSection", parent=styles["Heading2"], fontName="Helvetica-Bold",
        fontSize=11, leading=14, textColor=NAVY, spaceBefore=10, spaceAfter=7,
    ))
    styles.add(ParagraphStyle(
        name="KFBCell", parent=styles["Normal"], fontName="Helvetica",
        fontSize=7.7, leading=10, textColor=INK,
    ))
    styles.add(ParagraphStyle(
        name="KFBCellRight", parent=styles["KFBCell"], alignment=TA_RIGHT,
    ))
    styles.add(ParagraphStyle(
        name="KFBKpiLabel", parent=styles["Normal"], fontName="Helvetica-Bold",
        fontSize=7.3, leading=9, textColor=MUTED,
    ))
    styles.add(ParagraphStyle(
        name="KFBKpiValue", parent=styles["Normal"], fontName="Helvetica-Bold",
        fontSize=12, leading=15, textColor=NAVY,
    ))
    return styles


def _decorate_page(canvas, doc, *, hospital_name, classification):
    width, height = doc.pagesize
    canvas.saveState()

    canvas.setFillColor(colors.Color(0.08, 0.18, 0.31, alpha=0.055))
    canvas.setFont("Helvetica-Bold", 44)
    canvas.translate(width / 2, height / 2)
    canvas.rotate(32)
    canvas.drawCentredString(0, 0, "KFBH CONFIDENTIAL")
    canvas.restoreState()

    canvas.saveState()
    canvas.setStrokeColor(TEAL)
    canvas.setLineWidth(1.4)
    canvas.line(doc.leftMargin, height - 15 * mm, width - doc.rightMargin, height - 15 * mm)
    canvas.setFont("Helvetica-Bold", 8)
    canvas.setFillColor(NAVY)
    canvas.drawString(doc.leftMargin, height - 11.5 * mm, hospital_name)
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(MUTED)
    canvas.drawRightString(width - doc.rightMargin, height - 11.5 * mm, classification)
    canvas.line(doc.leftMargin, 12 * mm, width - doc.rightMargin, 12 * mm)
    canvas.drawString(doc.leftMargin, 7.5 * mm, "Generated from the accountable hospital ledger")
    canvas.drawRightString(width - doc.rightMargin, 7.5 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _build_document(story, *, hospital_name, title, landscape_mode=True):
    output = BytesIO()
    pagesize = landscape(A4) if landscape_mode else A4
    doc = SimpleDocTemplate(
        output,
        pagesize=pagesize,
        rightMargin=14 * mm,
        leftMargin=14 * mm,
        topMargin=21 * mm,
        bottomMargin=18 * mm,
        title=title,
        author=hospital_name,
        subject="Confidential hospital report",
    )
    def callback(canvas, current_doc):
        _decorate_page(
            canvas,
            current_doc,
            hospital_name=hospital_name,
            classification="CONFIDENTIAL - AUTHORISED USE ONLY",
        )

    doc.build(story, onFirstPage=callback, onLaterPages=callback)
    return output.getvalue()


def build_financial_report_pdf(*, context, hospital_name, generated_by):
    styles = _styles()
    period_label = "Last 24 hours" if context["days"] == 1 else f"Last {context['days']} days"
    generated_at = timezone.localtime(context["last_refresh"])
    story = [
        Paragraph("Owner financial and operations report", styles["KFBTitle"]),
        Paragraph(
            f"{_text(period_label)} | Generated {generated_at:%d %b %Y, %H:%M} EAT | "
            f"Generated by {_text(generated_by)}",
            styles["KFBMeta"],
        ),
        Spacer(1, 6 * mm),
    ]

    kpis = [
        ("NET BILLED CHARGES", _money(context["net_billed"]), "Posted lines in period"),
        ("VERIFIED COLLECTIONS", _money(context["verified_collections"]), "Cash and verified M-PESA"),
        ("UNVERIFIED M-PESA", _money(context["unverified_mpesa"]), "Excluded from verified collections"),
        ("RECEIVABLES", _money(context["receivables"]), "Current outstanding balance"),
    ]
    kpi_cells = []
    for label, value, note in kpis:
        kpi_cells.append([
            Paragraph(label, styles["KFBKpiLabel"]),
            Paragraph(value, styles["KFBKpiValue"]),
            Paragraph(_text(note), styles["KFBMeta"]),
        ])
    kpi_table = Table([kpi_cells], colWidths=[63 * mm] * 4, rowHeights=[24 * mm])
    kpi_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BACKGROUND", (0, 0), (-1, -1), colors.white),
        ("BOX", (0, 0), (-1, -1), 0.6, LINE),
        ("INNERGRID", (0, 0), (-1, -1), 0.6, LINE),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.extend([kpi_table, Spacer(1, 5 * mm)])

    departments = list(context["department_activity"])
    department_rows = [["Department", "Encounters"]]
    department_rows.extend([
        [Paragraph(_text(row["department"]), styles["KFBCell"]), str(row["total"])]
        for row in departments
    ])
    if len(department_rows) == 1:
        department_rows.append(["No activity in this period", "0"])
    department_table = Table(department_rows, colWidths=[80 * mm, 30 * mm], repeatRows=1)
    department_table.setStyle(_table_style(right_columns=(1,)))

    invoice_rows = [["Invoice", "Patient / customer", "Posted", "Total", "Balance", "Status"]]
    for invoice in context["recent_invoices"]:
        customer = invoice.patient.full_name if invoice.patient else invoice.customer_name
        invoice_rows.append([
            Paragraph(_text(invoice.invoice_number), styles["KFBCell"]),
            Paragraph(_text(customer), styles["KFBCell"]),
            timezone.localtime(invoice.posted_at).strftime("%d %b %Y %H:%M"),
            _money(invoice.total),
            _money(invoice.balance),
            invoice.get_status_display(),
        ])
    if len(invoice_rows) == 1:
        invoice_rows.append(["No posted invoices", "", "", "", "", ""])
    invoice_table = Table(
        invoice_rows,
        colWidths=[34 * mm, 55 * mm, 37 * mm, 34 * mm, 34 * mm, 27 * mm],
        repeatRows=1,
    )
    invoice_table.setStyle(_table_style(right_columns=(3, 4)))

    stock = context["stock"]
    stock_activity = context["stock_activity"]
    receiving = context["receiving"]
    stock_rows = [["Measure", "Value", "Basis"]]
    stock_rows.extend([
        [
            Paragraph(_text(label), styles["KFBCell"]),
            value,
            Paragraph(_text(basis), styles["KFBCell"]),
        ]
        for label, value, basis in [
            ("Stock value at cost", _money(stock["stock_value_cost"]), "Ledger balance at batch purchase cost"),
            (
                "Stock value at selling price",
                _money(stock["stock_value_retail"]),
                f"Excludes {stock['unpriced_item_count']} unpriced product(s)"
                if stock["unpriced_item_count"] else "All held products carry an approved price",
            ),
            ("Cost of goods dispensed", _money(stock_activity["cost_of_goods_dispensed"]), "Outward movements in period, at batch cost"),
            ("Product sales billed", _money(stock_activity["product_sales_value"]), "Posted product invoice lines in period"),
            ("Product gross margin", _money(stock_activity["product_gross_margin"]), "Billed less cost of goods; not an operating result"),
            ("Products below reorder level", str(stock["below_reorder_count"]), "Sellable stock only"),
            ("Batches expiring soon", str(stock["expiring_soon_count"]), f"Within {stock['expiry_window_days']} days, still holding stock"),
            ("Expired stock held", _money(stock["expired_value"]), f"{stock['expired_count']} batch(es), not sellable"),
            ("Deliveries awaiting check", str(receiving["unchecked_count"]), f"Of {receiving['receipt_count']} received in period"),
        ]
    ])
    stock_table = Table(stock_rows, colWidths=[62 * mm, 40 * mm, 78 * mm], repeatRows=1)
    stock_table.setStyle(_table_style(right_columns=(1,)))

    story.extend([
        KeepTogether([Paragraph("Department activity", styles["KFBSection"]), department_table]),
        Paragraph("Posted invoices", styles["KFBSection"]),
        invoice_table,
        Spacer(1, 5 * mm),
        Paragraph("Stock position", styles["KFBSection"]),
        stock_table,
        Spacer(1, 5 * mm),
        Paragraph(
            "Operating result is intentionally omitted because the cost basis is not fully configured. "
            "Unverified M-PESA is shown separately and is not counted as verified collection. "
            "Stock is valued at the recorded purchase cost of the batch each unit sits in; stock discrepancy "
            "against a physical count comes only from an approved stock count.",
            styles["KFBMeta"],
        ),
    ])
    return _build_document(
        story,
        hospital_name=hospital_name,
        title=f"KFBH owner report - {period_label}",
    )


def build_patient_access_pdf(*, patient, hospital_name, generated_by):
    styles = _styles()
    generated_at = timezone.localtime()
    story = [
        Paragraph("Patient access record", styles["KFBTitle"]),
        Paragraph(
            f"Patient {_text(patient.patient_number)} | Generated {generated_at:%d %b %Y, %H:%M} EAT | "
            f"Generated by {_text(generated_by)}",
            styles["KFBMeta"],
        ),
        Spacer(1, 5 * mm),
        Paragraph("Identity", styles["KFBSection"]),
    ]
    identity = [
        ["Full name", patient.full_name],
        ["Patient number", patient.patient_number],
        ["Date of birth / age", patient.date_of_birth or f"Estimated {patient.estimated_age_years} years"],
        ["Phone", patient.phone or "Not recorded"],
        ["National ID", patient.id_number or "Not recorded"],
        ["Allergy status", patient.get_allergy_status_display()],
        ["Allergy details", patient.allergy_details or "None recorded"],
    ]
    identity_table = Table(identity, colWidths=[48 * mm, 132 * mm])
    identity_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), PALE),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 0), (-1, -1), INK),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, LINE),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(identity_table)

    story.append(Paragraph("Visits", styles["KFBSection"]))
    visit_rows = [["Visit", "Started", "Department", "Urgency", "Status"]]
    for encounter in patient.encounters.all().order_by("created_at"):
        visit_rows.append([
            encounter.encounter_number,
            timezone.localtime(encounter.created_at).strftime("%d %b %Y %H:%M"),
            encounter.department,
            encounter.get_urgency_display(),
            encounter.get_status_display(),
        ])
    if len(visit_rows) == 1:
        visit_rows.append(["No visits recorded", "", "", "", ""])
    visit_table = Table(visit_rows, colWidths=[42 * mm, 41 * mm, 38 * mm, 28 * mm, 39 * mm], repeatRows=1)
    visit_table.setStyle(_table_style())
    story.append(visit_table)

    notes = patient.encounters.prefetch_related("clinical_notes__author").all()
    story.append(Paragraph("Signed clinical notes", styles["KFBSection"]))
    note_rows = [["Date", "Author", "Assessment", "Plan"]]
    for encounter in notes:
        for note in encounter.clinical_notes.exclude(status="draft"):
            note_rows.append([
                timezone.localtime(note.created_at).strftime("%d %b %Y"),
                note.author.get_full_name() or note.author.username,
                Paragraph(_text(note.assessment or "Not recorded"), styles["KFBCell"]),
                Paragraph(_text(note.plan or "Not recorded"), styles["KFBCell"]),
            ])
    if len(note_rows) == 1:
        note_rows.append(["No signed notes", "", "", ""])
    note_table = Table(note_rows, colWidths=[29 * mm, 38 * mm, 60 * mm, 61 * mm], repeatRows=1)
    note_table.setStyle(_table_style())
    story.append(note_table)

    story.extend([
        Spacer(1, 5 * mm),
        Paragraph(
            "This export is a generated access copy, not an amendment to the clinical record. "
            "Draft notes and internal audit metadata are excluded.",
            styles["KFBMeta"],
        ),
    ])
    return _build_document(
        story,
        hospital_name=hospital_name,
        title=f"Patient access record - {patient.patient_number}",
        landscape_mode=False,
    )


def _table_style(*, right_columns=()):
    commands = [
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 7.4),
        ("LEADING", (0, 0), (-1, -1), 9.5),
        ("GRID", (0, 0), (-1, -1), 0.45, LINE),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, PALE]),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]
    for column in right_columns:
        commands.append(("ALIGN", (column, 1), (column, -1), "RIGHT"))
    return TableStyle(commands)
