# Generated by Django 5.2.17 on 2026-09-18 21:53

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill_human_references(apps, schema_editor):
    """Give any pre-existing row a reference before the unique index lands.

    Neither model had a creation screen before this migration, so in practice
    the tables are empty. Backfilling anyway keeps the migration safe on a
    database that was populated from a shell.
    """
    for model_name, field, prefix in [
        ("GoodsReceipt", "receipt_number", "GRN"),
        ("StockCount", "reference", "SC"),
    ]:
        model = apps.get_model("hospital", model_name)
        for row in model.objects.filter(**{field: ""}):
            stamp = getattr(row, "created_at", None)
            day = stamp.strftime("%Y%m%d") if stamp else "00000000"
            setattr(row, field, f"{prefix}-{day}-{uuid.uuid4().hex[:6].upper()}")
            row.save(update_fields=[field])


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0005_legacy_import_references"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goodsreceipt",
            options={"ordering": ["-delivered_at"]},
        ),
        migrations.AlterModelOptions(
            name="stockcount",
            options={"ordering": ["-cutoff_at"]},
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="delivered_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="invoice_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="invoice_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="invoice_photo",
            field=models.FileField(blank=True, upload_to="supplier_invoices/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="invoice_photo_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="receipt_number",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="goodsreceiptline",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipt_lines",
                to="hospital.stockbatch",
            ),
        ),
        migrations.AddField(
            model_name="stockcount",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="stockcount",
            name="reference",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.RunPython(backfill_human_references, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="goodsreceipt",
            name="receipt_number",
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="stockcount",
            name="reference",
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name="stockcount",
            name="review_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="stockcount",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="goodsreceiptline",
            name="order_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipt_lines",
                to="hospital.purchaseorderline",
            ),
        ),
        migrations.AlterField(
            model_name="stockcount",
            name="status",
            field=models.CharField(
                choices=[
                    ("frozen", "Snapshot frozen"),
                    ("submitted", "Submitted for review"),
                    ("approved", "Approved and posted"),
                    ("rejected", "Rejected"),
                ],
                default="frozen",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="stockcountline",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="count_lines",
                to="hospital.stockbatch",
            ),
        ),
    ]
