# Generated by Django 5.2.17 on 2026-09-19 07:24

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0006_goods_receipt_evidence_and_stock_counts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(blank=True, max_length=30, unique=True)),
                ("department", models.CharField(max_length=80)),
                ("received_by_name", models.CharField(max_length=160)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("patient", "Patient-specific"),
                            ("general", "General consumable"),
                        ],
                        default="general",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("outstanding", "In departmental custody"),
                            ("settled", "Fully accounted for"),
                        ],
                        default="outstanding",
                        max_length=14,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_issues",
                        to="hospital.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentIssueLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_issued",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "quantity_consumed",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=14
                    ),
                ),
                (
                    "quantity_returned",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=14
                    ),
                ),
                (
                    "quantity_wasted",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=14
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issue_lines",
                        to="hospital.stockbatch",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="hospital.departmentissue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockWriteOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(blank=True, max_length=30, unique=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("expired", "Expired"),
                            ("damaged", "Damaged or broken"),
                            ("contaminated", "Contaminated or unsafe"),
                            ("recalled", "Recalled by supplier or authority"),
                            ("other", "Other, described below"),
                        ],
                        max_length=16,
                    ),
                ),
                ("narrative", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting independent approval"),
                            ("approved", "Approved and posted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="write_offs",
                        to="hospital.stockbatch",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="write_offs_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="write_offs_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
