# Generated by Django 5.2.17 on 2026-09-19 18:53

import hashlib

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_exception_dedupe_keys(apps, schema_editor):
    """Give every existing exception the key new code will look it up by.

    Without this the first recurrence of an already-recorded problem creates a
    second row beside the old one, and the history of that exception splits in
    two. Rows that would collide keep a blank key, which the partial unique
    constraint ignores, so the migration cannot fail on legacy duplicates.
    """
    ExceptionRecord = apps.get_model("hospital", "ExceptionRecord")
    seen = set()
    updates = []
    for record in ExceptionRecord.objects.all().order_by("pk").iterator():
        key = hashlib.sha256(f"{record.category}:{record.summary}".encode()).hexdigest()[:64]
        if key in seen:
            continue
        seen.add(key)
        record.dedupe_key = key
        record.last_seen_at = record.updated_at or record.created_at
        updates.append(record)
        if len(updates) >= 500:
            ExceptionRecord.objects.bulk_update(updates, ["dedupe_key", "last_seen_at"])
            updates = []
    if updates:
        ExceptionRecord.objects.bulk_update(updates, ["dedupe_key", "last_seen_at"])


def backfill_mpesa_references(apps, schema_editor):
    """Mark pre-existing M-PESA payments that carry no reference.

    The new constraint forbids them going forward. Any that already exist are
    real money the hospital took, so they are labelled for investigation rather
    than deleted or blocked — and the label is what the constraint needs.
    """
    Payment = apps.get_model("hospital", "Payment")
    updates = []
    for payment in Payment.objects.filter(method="mpesa", reference="").iterator():
        # A per-row save() raises if the row has moved underneath the migration
        # and aborts the whole upgrade. A bulk update cannot.
        identifier = payment.pk.hex if hasattr(payment.pk, "hex") else str(payment.pk).replace("-", "")
        payment.reference = f"MISSING-{identifier[:12].upper()}"
        payment.verification_status = "unverified"
        updates.append(payment)
        if len(updates) >= 500:
            Payment.objects.bulk_update(updates, ["reference", "verification_status"])
            updates = []
    if updates:
        Payment.objects.bulk_update(updates, ["reference", "verification_status"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0007_departmental_custody_and_write_offs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exceptionrecord",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="exceptionrecord",
            name="dedupe_key",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="exceptionrecord",
            name="last_seen_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="exceptionrecord",
            name="occurrence_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name="departmentissue",
            index=models.Index(
                fields=["status", "issued_at"], name="hospital_de_status_63310d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="departmentissue",
            index=models.Index(
                fields=["department"], name="hospital_de_departm_de4916_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exceptionrecord",
            index=models.Index(
                fields=["status", "severity"], name="hospital_ex_status_8613e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exceptionrecord",
            index=models.Index(
                fields=["category"], name="hospital_ex_categor_71646c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goodsreceipt",
            index=models.Index(
                fields=["delivered_at"], name="hospital_go_deliver_1e0de3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goodsreceipt",
            index=models.Index(
                fields=["checked_by", "delivered_at"],
                name="hospital_go_checked_2e62b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["method", "verification_status"],
                name="hospital_pa_method_445226_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["received_at"], name="hospital_pa_receive_a28fd0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "received_at"], name="hospital_pa_status_9b39d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="priceversion",
            index=models.Index(
                fields=["item", "effective_from", "effective_to"],
                name="hospital_pr_item_id_88491d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["item", "status"], name="hospital_st_item_id_d28cba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["status", "expiry_date"], name="hospital_st_status_289e53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["batch", "event_at"], name="hospital_st_batch_i_fc830a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["movement_type", "event_at"],
                name="hospital_st_movemen_27ccd3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["event_at"], name="hospital_st_event_a_c16fb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["reference_type", "reference_id"],
                name="hospital_st_referen_11f547_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockwriteoff",
            index=models.Index(
                fields=["status", "created_at"], name="hospital_st_status_cfd6ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockwriteoff",
            index=models.Index(
                fields=["batch", "status"], name="hospital_st_batch_i_b4d630_idx"
            ),
        ),
        migrations.RunPython(backfill_exception_dedupe_keys, noop),
        migrations.RunPython(backfill_mpesa_references, noop),
        migrations.AddConstraint(
            model_name="exceptionrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dedupe_key", ""), _negated=True),
                fields=("dedupe_key",),
                name="unique_exception_dedupe_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("method", "mpesa"), _negated=True),
                    models.Q(("reference", ""), _negated=True),
                    _connector="OR",
                ),
                name="mpesa_payment_requires_reference",
            ),
        ),
    ]
