# Generated by Django 5.2.17 on 2026-09-29 20:20

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def reject_existing_duplicate_references(apps, schema_editor):
    # A duplicate may represent two different people or debts. Never guess
    # which row to merge or delete during a schema migration.
    for model_name in ("Patient", "Invoice"):
        model = apps.get_model("hospital", model_name)
        duplicates = (
            model.objects.using(schema_editor.connection.alias)
            .exclude(external_reference="")
            .values("external_reference")
            .annotate(total=Count("pk"))
            .filter(total__gt=1)
        )
        if duplicates.exists():
            raise RuntimeError(
                f"{model_name} has duplicate nonblank external references. "
                "Reconcile those records before applying migration 0009; no rows were changed."
            )


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_production_hardening_indexes_and_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(reject_existing_duplicate_references, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('external_reference', ''), _negated=True), fields=('external_reference',), name='unique_invoice_external_reference'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('external_reference', ''), _negated=True), fields=('external_reference',), name='unique_patient_external_reference'),
        ),
    ]
