# Generated by Django 5.2.17 on 2026-09-29 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_unique_legacy_import_references'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcount',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['entered_at', 'event_at'], name='hospital_st_entered_a58351_idx'),
        ),
    ]
