# Generated by Django 5.2.17 on 2026-09-29 20:40

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q, Sum


def reopen_invoices_with_pending_mpesa(apps, schema_editor):
    Invoice = apps.get_model('hospital', 'Invoice')
    InvoiceLine = apps.get_model('hospital', 'InvoiceLine')
    CreditNote = apps.get_model('hospital', 'CreditNote')
    PaymentAllocation = apps.get_model('hospital', 'PaymentAllocation')
    Payment = apps.get_model('hospital', 'Payment')
    Payment.objects.filter(
        method='mpesa', status='valid', verification_status__in=['manual', 'provider'],
        reviewed_at__isnull=True,
    ).update(reviewed_at=models.F('updated_at'))
    affected_ids = PaymentAllocation.objects.filter(
        payment__method='mpesa', payment__status='valid',
        payment__verification_status='unverified',
    ).values_list('invoice_id', flat=True).distinct()
    for invoice in Invoice.objects.filter(pk__in=affected_ids).exclude(status='draft').iterator():
        billed = InvoiceLine.objects.filter(invoice_id=invoice.pk).aggregate(v=Sum('line_total'))['v'] or Decimal('0.00')
        credits = CreditNote.objects.filter(invoice_id=invoice.pk, status='approved').aggregate(v=Sum('amount'))['v'] or Decimal('0.00')
        paid = PaymentAllocation.objects.filter(
            invoice_id=invoice.pk, payment__status='valid',
        ).filter(
            Q(payment__method='cash')
            | Q(payment__verification_status__in=['manual', 'provider'])
        ).aggregate(v=Sum('amount'))['v'] or Decimal('0.00')
        balance = billed - credits - paid
        status = 'paid' if balance <= 0 else ('part_paid' if paid > 0 else 'posted')
        Invoice.objects.filter(pk=invoice.pk).update(status=status)


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_stockcount_submitted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('rejected', 'Rejected claim'), ('reversed', 'Reversed')], default='valid', max_length=12),
        ),
        migrations.RunPython(reopen_invoices_with_pending_mpesa, migrations.RunPython.noop),
    ]
