# Generated by Django 5.2.17 on 2026-09-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_payment_review_notes_payment_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
