# Generated by Django 5.2.17 on 2026-09-29 20:56

from decimal import Decimal

from django.db import migrations, models

PRECISION = Decimal('0.000001')


def backfill_moving_average_costs(apps, schema_editor):
    alias = schema_editor.connection.alias
    Batch = apps.get_model('hospital', 'StockBatch')
    Movement = apps.get_model('hospital', 'StockMovement')
    ReceiptLine = apps.get_model('hospital', 'GoodsReceiptLine')
    initial_costs = dict(Batch.objects.using(alias).values_list('pk', 'purchase_cost_per_base_unit'))

    # Several lines of one supplier receipt can name the same batch. Their
    # quantity-weighted invoice cost is the only defensible historical rate.
    receipt_totals = {}
    for batch_id, receipt_id, quantity, cost in ReceiptLine.objects.using(alias).exclude(
        batch_id__isnull=True,
    ).values_list('batch_id', 'receipt_id', 'quantity_received', 'actual_unit_cost').iterator():
        key = (batch_id, str(receipt_id))
        value, units = receipt_totals.get(key, (Decimal('0'), Decimal('0')))
        receipt_totals[key] = (value + quantity * cost, units + quantity)
    receipt_costs = {
        key: (value / units).quantize(PRECISION)
        for key, (value, units) in receipt_totals.items() if units > 0
    }

    current_batch_id = None
    balance = Decimal('0')
    average_cost = Decimal('0')
    updates = []
    movements = Movement.objects.using(alias).order_by('batch_id', 'entered_at', 'pk').iterator(chunk_size=500)
    for movement in movements:
        if movement.batch_id != current_batch_id:
            if current_batch_id is not None:
                Batch.objects.using(alias).filter(pk=current_batch_id).update(purchase_cost_per_base_unit=average_cost)
            current_batch_id = movement.batch_id
            balance = Decimal('0')
            average_cost = initial_costs[current_batch_id]
        delta = movement.quantity_delta
        if movement.movement_type == 'receipt' and delta > 0:
            receipt_cost = receipt_costs.get((movement.batch_id, movement.reference_id), average_cost)
            average_cost = (
                ((balance * average_cost + delta * receipt_cost) / (balance + delta))
                if balance > 0 else receipt_cost
            ).quantize(PRECISION)
            movement.unit_cost_at_event = receipt_cost
        else:
            movement.unit_cost_at_event = average_cost
        balance += delta
        updates.append(movement)
        if len(updates) == 500:
            Movement.objects.using(alias).bulk_update(updates, ['unit_cost_at_event'])
            updates.clear()
    if updates:
        Movement.objects.using(alias).bulk_update(updates, ['unit_cost_at_event'])
    if current_batch_id is not None:
        Batch.objects.using(alias).filter(pk=current_batch_id).update(purchase_cost_per_base_unit=average_cost)


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_clinicalnote_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='unit_cost_at_event',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='purchase_cost_per_base_unit',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18),
        ),
        migrations.RunPython(backfill_moving_average_costs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='stockmovement',
            name='unit_cost_at_event',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
    ]
