# Generated by Django 5.2.17 on 2026-09-29 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_admission_discharged_by_encounter_closed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='service_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charge_line', to='hospital.serviceorder'),
        ),
    ]
