# Generated by Django 5.2.17 on 2026-09-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_serviceorder_reviewed_at_serviceorder_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='amendment_reason',
            field=models.TextField(blank=True),
        ),
    ]
