# Generated by Django 5.2.17 on 2026-09-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_payment_receipt_issued_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['ip_address', 'attempted_at'], name='hospital_lo_ip_addr_f2cae4_idx'),
        ),
    ]
